name: AquaAnnouncement
version: ${project.version}
author: Shiryu
main: io.github.shiryu.aquaannouncement.bukkit.AquaAnnouncement
softdepend: [PlaceholderAPI]
depend: [ProtocolLib]

commands:
